apiVersion: apps/v1
kind: Deployment
metadata:
  name: "tomcat-{{ .Values.appName }}-deployment"
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "tomcat-{{ .Values.appName }}"
  template:
    metadata:
      labels:
        app: "tomcat-{{ .Values.appName }}"
    spec:
      containers:
        - name: "tomcat-{{ .Values.appName }}"
          image: {{ .Values.appImage }}
          ports:
            - containerPort: 8080