apiVersion: v1
kind: Service
{{ $apiName := .Values.appName }}
metadata:
  name: "{{ $apiName }}-service"
  namespace: argocd
spec:
  type: NodePort
  selector:
    app: "tomcat-{{ $apiName }}"
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 32227